[main]
magic = 14
datadir = "/home/user/.moon/share/why3"
libdir = "/home/user/.moon/lib/why3"
memlimit = 1000
running_provers_max = 16
timelimit = 180.000000

[partial_prover]
name = "Z3"
path = "/usr/local/bin/z3"
version = "5.1.0"

[partial_prover]
name = "CVC5"
path = "/usr/local/bin/cvc5"
version = "1.4.2"

[strategy]
code = "start:
c Z3,5.1.0 .2 20000
c Z3,5.1.0 1 50000
t compute_specified start
t split_vc start
c Z3,5.1.0 2 500000
c CVC5,1.4.2 .2 20000
c CVC5,1.4.2 1 50000
c CVC5,1.4.2 2 500000
"
desc = "Automatic@ run@ of@ provers@ and@ most@ useful@ transformations"
name = "MoonBit_Auto"
shortcut = "4"
